### ISSUE TITLE
font-awesome for dfwc/icon component

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#105]
I did a component for font-awesome icons that maybe could be integrated here

### Component

```js
import {
  LitElement, html, customElement, property, css
} from 'lit-element';

import { library, icon, config, dom } from '@fortawesome/fontawesome-svg-core'
import { faSort, faSortUp, faSortDown } from '@fortawesome/free-solid-svg-icons'

config.autoAddCss = false
library.add(faSort, faSortUp, faSortDown)

const icons = {
  "sort": icon(faSort),
  "sort-up": icon(faSortUp),
  "sort-down": icon(faSortDown),
}


@customElement('df-icon')
export class Icon extends LitElement {
  @property({type: String}) icon: String;

  static get styles () {
    return [
      css([dom.css()])
    ]
  }

  public render(){
    let icon = icons[this.icon];

    if (icon)
      return html(icon.html)
    return html`<p> icon not found </p>`
  }
}
```

requirements
* @fortawesome/fontawesome-svg-core
* @fortawesome/free-solid-svg-icons

Sample usage: `<df-icon icon="sort-up"></df-icon>`

This is the component that I did that needs more work to be more dynamic of course. It has a very nice stuff, could be loaded only the required icon and just them by importing and adding to the library, so it optimizes size of package (not all icons loaded)

**Comment by carlosescri** [comment]
The current df-icon imports a webfont into the owner document. Is there a way to do the same? This way you don't have to add specific icons but just use them.

**Comment by sonic182** [comment]
This way to use fontawesome, generates the svg html from javascript

The normal way of using fontawesome in html is by inserting fontawesome css and js and it will replace the <i> icons to <svg> tags

So we just need a way to import all icons and I guess it will be ok

**Comment by sonic182** [comment]
References

* https://www.npmjs.com/package/@fortawesome/fontawesome-svg-core
* https://fontawesome.com/how-to-use/with-the-api/setup/getting-started

**Comment by sonic182** [comment]
This way the component has all icons loaded (notice the load of **fas**)

The usage of `{prefix: 'fas', ...` is to specify that the **iconName** is in the package of **free solid svg icons**, font-awesome has more icons libraries that could be loaded and could be used by loading those icons and specifying the correct **prefix** and **iconName**, another icons library they have is the **brand** icons https://www.npmjs.com/package/@fortawesome/free-brands-svg-icons
