### ISSUE TITLE
(1) [widget] Banner component

### ISSUE THREAD

**Issue by resetreboot** [doofinder/webcomponents#15]
Make sure we have a component to load and show banners when necessary.

- [x] Create the component.
- [x] Obtain the configuration data.
- [x] Tie it up to the stats system to register events: display and click.

**Comment by carlosescri** [comment]
Which configuration data?

**Comment by resetreboot** [comment]
Without knowing much about the banners, I'd go with the image url, first, and when to show up second (query, etc...)

**Comment by carlosescri** [comment]
Ah, ok, sorry, component properties and that kind of stuff… The banner only has to display what the search response provides, so… 

- We need a component that displays when there's a banner and hides in other case.
- Paints a link (if any?, I don't remember if there's always a link, probably yes)
- Displays the image.
- Sends stats when the image is clicked.
