### ISSUE TITLE
(0.5) Don't export instances of the singletons, just the classes

### ISSUE THREAD

**Issue by carlosescri** [doofinder/webcomponents#153]
The user will decide how to call them, so instead of:

```ts
import { store } from '@dfwc/core';
```

it would be more explicit:

```ts
import { Store } from '@dfwc/core';

const whatever = Store.getInstance();
```

There're some singletons apart from `store`.

**Comment by carlosescri** [comment]
**WARNING:** `clientPool` is OK as is.

**Comment by carlosescri** [comment]
> **WARNING:** `clientPool` is OK as is.

See #171, we may end doing `ClientPool.getInstance()` too!

**Comment by hailem** [comment]
Finally, we decided to export the singleton object and not the class.
