### ISSUE TITLE
[core] Options call loading

### ISSUE THREAD

**Issue by resetreboot** [doofinder/webcomponents#16]
Right now, no one's in charge of loading the options configured in the Search Engine, think where this data is fetched and stored, and how to make it available to the contexts or widgets that may need it.

**Comment by carlosescri** [comment]
Ok, the checkout URL is a good example. Let this issue opened for the moment.

**Comment by carlosescri** [comment]
My current list of options required by the components:

- Language code (`EN`, `ES`, `FR`, …)
- Currency code (`EUR`, `USD`, …)
- Any stats stuff (like checkout url) (related to #14 / #38)

**Comment by carlosescri** [comment]
Related to #92

**Comment by carlosescri** [comment]
Closed in favor of #92
