### ISSUE TITLE
Voice component throws an error in unsupported browsers

### ISSUE THREAD

**Issue by carlosescri** [doofinder/webcomponents#337]
<img width="511" alt="imagen" src="https://user-images.githubusercontent.com/482075/83023794-b3477a80-a02d-11ea-94a8-3a04d3b679d8.png">

**Comment by sonic182** [comment]
@carlosescri which demo? I think this is fixed already

**Comment by carlosescri** [comment]
Firefox throws that error with code in master.

**Comment by carlosescri** [comment]
See Fullscreen - RAW
