### ISSUE TITLE
(1) mediaQueryList.addEventListener is not a function In the latest safari ios

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#343]
![image](https://user-images.githubusercontent.com/4070466/83251052-54a70b80-a1a9-11ea-9069-b932fb3e1f48.png)

`mediaQueryList.addEventListener is not a function` In the latest safari ios

I guess a polyfill it's needed for [this experimental feature](https://developer.mozilla.org/es/docs/Web/API/MediaQueryList) (or just not to use this)

**Comment by sonic182** [comment]
Same for Edge non chrome based (Edge 18), but this shouldn't be a problem because windows updates make users to use the latest edge

![image](https://user-images.githubusercontent.com/4070466/83251945-b1ef8c80-a1aa-11ea-8c1c-d0791a4e572f.png)

**Comment by sonic182** [comment]
Safair in OS X breaks too (as IOS)

![image](https://user-images.githubusercontent.com/4070466/83252129-01ce5380-a1ab-11ea-9292-f1b67effcb6e.png)

I guess we'll have to use another standard stuff for this

**Comment by carlosescri** [comment]
Probably `addListener` will work for those instead of `addEventListener`. Seems that in iOS Safari `MediaQueryList` doesn't inherit / implement `EventTarget` API.

**Comment by carlosescri** [comment]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaQueryList/addListener):

![image](https://user-images.githubusercontent.com/482075/83255693-2e856980-a1b1-11ea-823c-64ed8b144fd6.png)
