### ISSUE TITLE
Infinite search

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#77]
When you remove

```html
<div class="df-aside">
                    <df-panel label="Filter by Category">
                        <df-term-list field="categories"></df-term-list>
                    </df-panel>
                    <df-panel label="Filter by Brand">
                        <df-term-list field="brand"></df-term-list>
                    </df-panel>
                    <df-panel label="Filter by Price">
                        <df-range-filter field="best_price" currency></df-range-filter>
                    </df-panel>
                </div>
```

From classic layer demo, it make searchs infinetly and set "undefined" in input

![imagen](https://user-images.githubusercontent.com/4070466/71910257-e28a4780-3171-11ea-8b18-da7d7c54ebcc.png)

**Comment by carlosescri** [comment]
I think this is the same as #76

**Comment by sonic182** [comment]
![imagen](https://user-images.githubusercontent.com/4070466/71968171-a94ee780-3204-11ea-9b00-f45d23c70870.png)

When it is few results this is not a problem, I think the issue is with the infinite scroll component @carlosescri
