### ISSUE TITLE
(1) [terms] Terms filter features

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#91]
~~For example, in the **df-term** component I would like to remove the counter~~

**Edit by @carlosescri**
- [ ] Count should be optional (use CSS var).
- [ ] Add checkbox style UI (optional via CSS var).

![25E3AF2A-0B12-4190-B4B0-EBCCA46A18B1](https://user-images.githubusercontent.com/482075/75795009-f4532a00-5d71-11ea-9f88-e2d45851b3c7.png)

**Comment by carlosescri** [comment]
Templates can be modified in certain components, but that's not the way to go in the vast majority of the cases. But we don't have a _framework_ / standard to follow with the CSS configuration.

In this case what you need is an option.
