### ISSUE TITLE
(3) Bootstrapper

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#92]
We need a build or a builder of layers, so customers could include v8 layer like this (I guess)

```html
<script src="https://cdn.doofinder.com/media/js/doofinder/v8.js?components=core,widgets"></script>
```

**Comment by carlosescri** [comment]
Currently we load the script as this:

```html
<script type="module">
  import '@dfwc/cards';
  // …
</script>
```

We can't use bare imports in browsers, we must import urls/paths:

```html
<script type="module">
  import '//cdn.doofinder.com/v8/cards.js';
  // …
</script>
```

This script will be used to add customizations:

```html
<script type="module">
  import '//cdn.doofinder.com/v8/cards.js';
  import { store, Zone } from '//cdn.doofinder.com/v8/core.js';

  const hashid = '…';
  const contextName = 'default';
  const zone = Zone.EU1;

  const context = store.getContext(hashid, contextName, zone);
  context.processor = (response) => {
    response.results = response.results.map(result => {
      result.ok = result.availability === 'in stock';
      return result;
    });
    return response;
  }
</script>
```

This script would be served from Doofinder servers like:

```html
<script type="module" src="//eu1-search.doofinder.com/5/script?hashid=…"></script>
```

or something like that, so we can _build_ the layer from the admin with a layer builder.

Other desirable features would be:

- Auto-detect which modules to load based on components found in the page.
- …?

**Comment by sonic182** [comment]
@carlosescri for the customization script, [Module Scripts](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) are not compatibles with internet explorer, neither edge :/ I guess we shouldn't do like that

**Comment by sonic182** [comment]
It looks like It's supported, It has the "88%" of the web right now https://caniuse.com/#search=module%20scripts%20import

**Comment by carlosescri** [comment]
Why can't use dynamic imports yet, but I think we can use module imports.

**Comment by carlosescri** [comment]
From #92:

> My current list of options required by the components:
>
> - Language code (EN, ES, FR, …)
> - Currency code (EUR, USD, …)
> - Any stats stuff (like checkout url) (related to #14 / #38)
