### ISSUE TITLE
After using setInitialSearchstate doesn't work queries

### ISSUE THREAD

**Issue by sonic182** [doofinder/webcomponents#97]
related: https://github.com/doofinder/webcomponents/issues/70

```js
  setupContext(){
    let context = this.context;
    let defaultParams = {
      // rpp: "100",
      // page: 1,
      autofilters: "true",
      phrasesextractor: "true",
      lang: "es",
      nlp: "true",
      smcategories: "true"
    };
    // context.processor = (res) => this.responseProcessor(res)
    context.setInitialSearchState(this.layer.hashid, defaultParams)
  }
```

When setting new initial search state, the first 3 characters query works, but the nexts queries when inserting more info at the input doesn't render the new data (keeps the old data rendered)

I also did this and didn't worked

```js
  setupContext(){
    let context = this.context;
    let defaultParams = { };
    // context.processor = (res) => this.responseProcessor(res)
    context.setInitialSearchState(this.layer.hashid, defaultParams)
  }
```

When not using `context.setInitialSearchState(this.layer.hashid, defaultParams)` works as expected

**Comment by carlosescri** [comment]
That method does not exist anymore so this is invalid.
